version: '3.8'
services:
  db:
    image: postgres:16-alpine
    container_name: horaspro-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: horaspro
      POSTGRES_PASSWORD: horaspro_dev
      POSTGRES_DB: horaspro_dev
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
